fix keystore issue in cp and per gw hostname format.

diff --git a/Deployment/apim-321-fully-distributed-multi-dc/dc-1/templates/am/gateway/deployment-1/apim-321-multi-dc-aks-am-gateway-deployment-1.yaml b/Deployment/apim-321-fully-distributed-multi-dc/dc-1/templates/am/gateway/deployment-1/apim-321-multi-dc-aks-am-gateway-deployment-1.yaml
--- a/Deployment/apim-321-fully-distributed-multi-dc/dc-1/templates/am/gateway/deployment-1/apim-321-multi-dc-aks-am-gateway-deployment-1.yaml
+++ b/Deployment/apim-321-fully-distributed-multi-dc/dc-1/templates/am/gateway/deployment-1/apim-321-multi-dc-aks-am-gateway-deployment-1.yaml
@@ -47,21 +47,19 @@ spec:
       - name: init-tm-2
         image: busybox:1.32
         command: ['sh', '-c', 'echo -e "Checking for the availability of TM instance two deployment"; while ! nc -z {{ template "apim-321-multi-dc-aks.resource.prefix" . }}-am-tm-2-internal-service 9611; do sleep 1; printf "-"; done; echo -e "  >> TM instance two has started";']
-      - name: init-permissions-synapse
-        image: busybox
-#        command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs/.snapshot*' -exec chmod 777 {} +" ]
-        command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs...';
-                    find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs/.snapshot*' -exec chmod 777 {} +;
-                    if [ $? -eq 0 ]; then
-                      echo 'Permissions set successfully for synapse mount.';
-                    else
-                      echo 'Error setting permissions for synapse mount, please check the NFS server settings.';
-                    fi;"
-        ]
-        volumeMounts:
-          - name: wso2am-gateway-storage-volume
+#      - name: init-permissions-synapse
+#        image: busybox
+#        command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs...';
+#                    find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs/.snapshot*' -exec chmod 777 {} +;
+#                    if [ $? -eq 0 ]; then
+#                      echo 'Permissions set successfully for synapse mount.';
+#                    else
+#                      echo 'Error setting permissions for synapse mount, please check the NFS server settings.';
+#                    fi;"
+#        ]
+#        volumeMounts:
+#          - name: wso2am-gateway-storage-volume
 #            mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs
-            mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/synapse-configs
       - name: init-permissions-logs
         image: busybox
 #        command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
diff --git a/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/tm/instance-1/apim-321-multi-dc-aks-am-tm-1-deployment.yaml b/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/tm/instance-1/apim-321-multi-dc-aks-am-tm-1-deployment.yaml
--- a/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/tm/instance-1/apim-321-multi-dc-aks-am-tm-1-deployment.yaml
+++ b/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/tm/instance-1/apim-321-multi-dc-aks-am-tm-1-deployment.yaml
@@ -54,7 +54,6 @@ spec:
           command: ['sh', '-c', 'echo -e "Checking for the availability of Key Manager deployment"; while ! nc -z {{ template "apim-321-multi-dc-aks.resource.prefix" . }}-am-km-service 9443; do sleep 1; printf "-"; done; echo -e "  >> Key Manager has started";']
         - name: init-permissions-logs
           image: busybox
-#          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
           command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/logs...';
                       find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +;
                       if [ $? -eq 0 ]; then
@@ -66,62 +65,58 @@ spec:
           volumeMounts:
             - name: wso2am-tm-log-storage-volume
               mountPath: /home/wso2carbon/wso2am-3.2.1/repository/logs
-        - name: init-permissions-executionplans
-          image: busybox
-          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
-          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/executionplans...';
-                    find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans/.snapshot*' -exec chmod 777 {} +;
-                    if [ $? -eq 0 ]; then
-                      echo 'Permissions set successfully.';
-                    else
-                      echo 'Error setting permissions, please check the NFS server settings.';
-                    fi;"
-          ]
-          volumeMounts:
-            - name: wso2am-tm-shared-executionplans-storage-volume
-              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans
-        - name: init-permissions-eventpublishers
-          image: busybox
-          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
-          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventpublishers...';
-                find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers/.snapshot*' -exec chmod 777 {} +;
-                if [ $? -eq 0 ]; then
-                  echo 'Permissions set successfully.';
-                else
-                  echo 'Error setting permissions, please check the NFS server settings.';
-                fi;"
-          ]
-          volumeMounts:
-            - name: wso2am-tm-shared-eventpublishers-storage-volume
-              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers
-        - name: init-permissions-eventreceivers
-          image: busybox
-          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
-          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventreceivers...';
-                find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers/.snapshot*' -exec chmod 777 {} +;
-                if [ $? -eq 0 ]; then
-                  echo 'Permissions set successfully.';
-                else
-                  echo 'Error setting permissions, please check the NFS server settings.';
-                fi;"
-          ]
-          volumeMounts:
-            - name: wso2am-tm-shared-eventreceivers-storage-volume
-              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers
-        - name: init-permissions-eventstreams
-          image: busybox
-          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
-          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventstreams...';
-            find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams/.snapshot*' -exec chmod 777 {} +;
-            if [ $? -eq 0 ]; then
-              echo 'Permissions set successfully.';
-            else
-              echo 'Error setting permissions, please check the NFS server settings.';
-            fi;"
-          ]
-          volumeMounts:
-            - name: wso2am-tm-shared-eventstreams-storage-volume
-              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams
+#        - name: init-permissions-executionplans
+#          image: busybox
+#          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/executionplans...';
+#                    find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans/.snapshot*' -exec chmod 777 {} +;
+#                    if [ $? -eq 0 ]; then
+#                      echo 'Permissions set successfully.';
+#                    else
+#                      echo 'Error setting permissions, please check the NFS server settings.';
+#                    fi;"
+#          ]
+#          volumeMounts:
+#            - name: wso2am-tm-shared-executionplans-storage-volume
+#              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans
+#        - name: init-permissions-eventpublishers
+#          image: busybox
+#          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventpublishers...';
+#                find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers/.snapshot*' -exec chmod 777 {} +;
+#                if [ $? -eq 0 ]; then
+#                  echo 'Permissions set successfully.';
+#                else
+#                  echo 'Error setting permissions, please check the NFS server settings.';
+#                fi;"
+#          ]
+#          volumeMounts:
+#            - name: wso2am-tm-shared-eventpublishers-storage-volume
+#              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers
+#        - name: init-permissions-eventreceivers
+#          image: busybox
+#          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventreceivers...';
+#                find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers/.snapshot*' -exec chmod 777 {} +;
+#                if [ $? -eq 0 ]; then
+#                  echo 'Permissions set successfully.';
+#                else
+#                  echo 'Error setting permissions, please check the NFS server settings.';
+#                fi;"
+#          ]
+#          volumeMounts:
+#            - name: wso2am-tm-shared-eventreceivers-storage-volume
+#              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventreceivers
+#        - name: init-permissions-eventstreams
+#          image: busybox
+#          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventstreams...';
+#            find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams/.snapshot*' -exec chmod 777 {} +;
+#            if [ $? -eq 0 ]; then
+#              echo 'Permissions set successfully.';
+#            else
+#              echo 'Error setting permissions, please check the NFS server settings.';
+#            fi;"
+#          ]
+#          volumeMounts:
+#            - name: wso2am-tm-shared-eventstreams-storage-volume
+#              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams
       containers:
         - name: wso2am-tm
           image: {{ .Values.wso2.deployment.am.image.registry }}/{{ .Values.wso2.deployment.am.image.repository }}:{{ .Values.wso2.deployment.am.image.tag }}
