update entrypoint.sh in gw.

diff --git a/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/gateway/apim-321-multi-dc-aks-am-gateway-conf-entrypoint.yaml b/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/gateway/apim-321-multi-dc-aks-am-gateway-conf-entrypoint.yaml
--- a/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/gateway/apim-321-multi-dc-aks-am-gateway-conf-entrypoint.yaml
+++ b/Deployment/apim-321-fully-distributed-multi-dc/dc-2/templates/am/gateway/apim-321-multi-dc-aks-am-gateway-conf-entrypoint.yaml
@@ -41,17 +41,17 @@ data:
     # if the original directory locations of artifacts to be synced between nodes are empty,
     # copy the preserved, default content of these folders to these original locations
     for shared_directory in ${directories[@]}; do
-    if test -d ${original_deployment_artifacts}/${shared_directory};
-    then
-    if [[ -z "$(ls -A ${deployment_volume}/${shared_directory})" ]]; then
-    if ! cp -R ${original_deployment_artifacts}/${shared_directory}/* ${deployment_volume}/${shared_directory};
-    then
-    echo "Failed to copy the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
-    exit 1
-    fi
-    echo "Successfully copied the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
-    fi
-    fi
+      if test -d ${original_deployment_artifacts}/${shared_directory};
+      then
+        if [[ -z "$(ls -A ${deployment_volume}/${shared_directory})" ]]; then
+          if ! cp -R ${original_deployment_artifacts}/${shared_directory}/* ${deployment_volume}/${shared_directory};
+          then
+            echo "Failed to copy the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
+            exit 1
+          fi
+          echo "Successfully copied the preserved, default artifacts to original location (${deployment_volume}/${shared_directory})"
+        fi
+      fi
     done
     
     # optimize WSO2 Carbon Server, if the profile name is defined as an environment variable
